### ISSUE TITLE
client_id und client_secret are not passed to terraform provider

### ISSUE THREAD

**Issue by schuhlisa** [glalanne/provider-databricks#10]
Hello

We are trying to use the provider with an aws databricks instance and a service account. In terraform it works following this guide:
https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog#provider-initializationhttps://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog#provider-initialization

**provider Initialization in terraform:**
```
provider "databricks" {
  alias         = "mws"
  host          = "https://accounts.cloud.databricks.com"
  account_id    = var.databricks_account_id
  client_id     = var.databricks_client_id
  client_secret = var.databricks_client_secret
`}`
```

But specifying the following credentials, always result in a credential error:
```
  message: 'apply failed: cannot create sql endpoint: failed creating warehouse:
      failed during request visitor: default auth: cannot configure default credentials,
      please check https://docs.databricks.com/en/dev-tools/auth.html#databricks-client-unified-authentication
      to configure credentials for your preferred authentication method. Config: host=https://xxx.cloud.databricks.com: 
```

**secret:**
```
apiVersion: v1
kind: Secret
metadata:
  name: databricks-credentials-playground
  namespace: databricks
type: Opaque
stringData:
  credentials: |
    {
      "host": "https://xxx.cloud.databricks.com",
      "client_id": "xxx",
      "client_secret": "xxx",
      "account_id": "xxx"
    }
```

**providerconfig:**
```
apiVersion: databricks.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: mws
spec:
  credentials:
    secretRef:
      key: credentials
      name: databricks-credentials-playground
      namespace: databricks
    source: Secret`
```
we checked the code and in internal/clients/databricks.go only azure_cliend_id and azure_client_secret is mapped.

Could you also add client_id and client_secret?

Thank you for your time :)
